// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdO14LhDF6kMYZBZTV_06jgSs1Xl8jvnQ',
    appId: '1:366767553733:web:fb7fb1e8b379dac7ebc4ac',
    messagingSenderId: '366767553733',
    projectId: 'salon-app-e1225',
    authDomain: 'salon-app-e1225.firebaseapp.com',
    storageBucket: 'salon-app-e1225.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC11d0fWqRHkx9fMN2wsjfAmTndl6hLdnU',
    appId: '1:366767553733:android:999cb8c63465cd0debc4ac',
    messagingSenderId: '366767553733',
    projectId: 'salon-app-e1225',
    storageBucket: 'salon-app-e1225.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz57Ih8jbeSKY2ietlm1z2Qu744n_DxqA',
    appId: '1:366767553733:ios:baf04d6b8bab1679ebc4ac',
    messagingSenderId: '366767553733',
    projectId: 'salon-app-e1225',
    storageBucket: 'salon-app-e1225.appspot.com',
    iosBundleId: 'com.example.salonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz57Ih8jbeSKY2ietlm1z2Qu744n_DxqA',
    appId: '1:366767553733:ios:6e1fe684fb4e9abbebc4ac',
    messagingSenderId: '366767553733',
    projectId: 'salon-app-e1225',
    storageBucket: 'salon-app-e1225.appspot.com',
    iosBundleId: 'com.example.salonApp.RunnerTests',
  );
}
